[[serial]]
PortName        = "COM1"
BaudRate        = 115200
MinimumReadSize = 4

[[serial]]
PortName        = "COM3"
BaudRate        = 115200
MinimumReadSize = 4

[[serial]]
PortName        = "COM5"
BaudRate        = 115200
MinimumReadSize = 4